/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.innovatrasolution.ui;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junai
 */
public class ManageCategory extends javax.swing.JFrame {

    /**
     * Creates new form ManageCategory
     */
    public ManageCategory() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add_categorybtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        deletercd_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        img_linklbl = new javax.swing.JLabel();
        warning_lbl = new javax.swing.JLabel();
        cat_name_txt1 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img_uploadlbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        category_tbl = new javax.swing.JTable();
        upload_imgbtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        search_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD CATEGORY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 280, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Category Image:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 30));

        add_categorybtn.setBackground(new java.awt.Color(102, 102, 102));
        add_categorybtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_categorybtn.setForeground(new java.awt.Color(255, 255, 255));
        add_categorybtn.setText("ADD CATEGORY");
        add_categorybtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        add_categorybtn.setContentAreaFilled(false);
        add_categorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_categorybtnActionPerformed(evt);
            }
        });
        jPanel1.add(add_categorybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 80, 30));

        deletercd_btn.setBackground(new java.awt.Color(102, 102, 102));
        deletercd_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deletercd_btn.setForeground(new java.awt.Color(255, 255, 255));
        deletercd_btn.setText("Delete");
        deletercd_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        deletercd_btn.setContentAreaFilled(false);
        deletercd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletercd_btnActionPerformed(evt);
            }
        });
        jPanel1.add(deletercd_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 130, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatrasolution/images/Images/crossbtn.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 30));

        img_linklbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(img_linklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 160, 30));

        warning_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        warning_lbl.setForeground(new java.awt.Color(204, 204, 0));
        warning_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warning_lbl.setText("*category name cannot be empty");
        jPanel1.add(warning_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 210, 20));

        cat_name_txt1.setBackground(new java.awt.Color(102, 102, 102));
        cat_name_txt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cat_name_txt1.setForeground(new java.awt.Color(255, 255, 255));
        cat_name_txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        cat_name_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_name_txt1ActionPerformed(evt);
            }
        });
        jPanel1.add(cat_name_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 210, 30));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jDesktopPane1.setForeground(new java.awt.Color(0, 0, 0));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(208, 212));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(208, 212));

        img_uploadlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_uploadlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jDesktopPane1.setLayer(img_uploadlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(img_uploadlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(img_uploadlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 150, 140));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 200));

        category_tbl.setBackground(new java.awt.Color(102, 102, 102));
        category_tbl.setBorder(new javax.swing.border.MatteBorder(null));
        category_tbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        category_tbl.setForeground(new java.awt.Color(255, 255, 255));
        category_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        category_tbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        category_tbl.setGridColor(new java.awt.Color(255, 255, 255));
        category_tbl.setIntercellSpacing(new java.awt.Dimension(0, 0));
        category_tbl.setMaximumSize(new java.awt.Dimension(50, 50));
        jScrollPane1.setViewportView(category_tbl);
        if (category_tbl.getColumnModel().getColumnCount() > 0) {
            category_tbl.getColumnModel().getColumn(0).setResizable(false);
            category_tbl.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 840, 210));

        upload_imgbtn1.setBackground(new java.awt.Color(102, 102, 102));
        upload_imgbtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        upload_imgbtn1.setForeground(new java.awt.Color(255, 255, 255));
        upload_imgbtn1.setText("Upload Image");
        upload_imgbtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        upload_imgbtn1.setContentAreaFilled(false);
        upload_imgbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_imgbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(upload_imgbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CATEGORIES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 270, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Category Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 30));

        search_txt.setBackground(new java.awt.Color(102, 102, 102));
        search_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search_txt.setForeground(new java.awt.Color(255, 255, 255));
        search_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_txtActionPerformed(evt);
            }
        });
        jPanel1.add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 170, 30));

        search_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatrasolution/images/Images/search-new.png"))); // NOI18N
        search_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_lblMouseClicked(evt);
            }
        });
        jPanel1.add(search_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_txtActionPerformed

    private void deletercd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletercd_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deletercd_btnActionPerformed

    Boolean CheckField(String CategoryName){
        
        if(!CategoryName.isEmpty()){
            return true;
        }
        else{
            return false;
        }
         
    }
    private void add_categorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_categorybtnActionPerformed
        // TODO add your handling code here:
        String url = "JDBC:sqlite:temp.db";
        Connection conn = null; 
        
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);
            
        }catch (ClassNotFoundException | SQLException ex){
            ex.getStackTrace();
        }
        
         String CategoryName = cat_name_txt1.getText();
         String ImgUrl = img_linklbl.getText();
         System.out.println(ImgUrl);
         
         
        if( CheckField(CategoryName) == true ){
            String query = "INSERT into category(category_name, category_image) VALUES(?,?);";
            try{
                
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, CategoryName);
                stmt.setString(2,ImgUrl);
                stmt.executeUpdate();
                CategoryAddedDialog dialog = new CategoryAddedDialog();
                dialog.setVisible(true);
                this.setVisible(false);
            } catch(SQLException ex){
                ex.getStackTrace();
            }
        }
        else if(CheckField(CategoryName)== false ){
            //Else incase of Category Textfield is null 
            warning_lbl.setVisible(true);
        }
    }//GEN-LAST:event_add_categorybtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        warning_lbl.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void upload_imgbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_imgbtn1ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser MyFileChooser = new JFileChooser();
        MyFileChooser.showOpenDialog(null);
        File MyFile = MyFileChooser.getSelectedFile();
        img_uploadlbl.setIcon(new ImageIcon(MyFile.toString()));
        FileName = MyFile.getAbsoluteFile().toString();
        img_linklbl.setText(FileName);
        
        try{
            File Image = new File(FileName);
            FileInputStream InputStream = new FileInputStream(Image);
            ByteArrayOutputStream OutputStream = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];
                for(int readNum; (readNum = InputStream.read(buffer))!= -1;){
                    OutputStream.write(buffer, 0, readNum);
                }
                Photo = OutputStream.toByteArray();
        }catch(IOException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
 
    }//GEN-LAST:event_upload_imgbtn1ActionPerformed

    private void cat_name_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_name_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_name_txt1ActionPerformed

    private void search_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_lblMouseClicked
        // TODO add your handling code here:
         String url = "JDBC:sqlite:temp.db";
        Connection conn = null; 
        
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);
            
        }catch (ClassNotFoundException | SQLException ex){
            ex.getStackTrace();
        }
        
        String query = "SELECT *from category;";
        try{
            PreparedStatement stmt = conn.prepareStatement(query);
                
                ResultSet res =stmt.executeQuery();
                
                while(res.next()){
                    String id = String.valueOf(res.getInt("category_id"));
                    
                    String CategoryName = res.getString("category_name");
                    
                    
                    String data[] = {id,CategoryName};
                    DefaultTableModel TblModel = (DefaultTableModel)category_tbl.getModel();
                    
                    
                    TblModel.addRow(data);
                }
                res.close();
                conn.close();
                
        }catch(SQLException ex){
            ex.getStackTrace();
        }
    }//GEN-LAST:event_search_lblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_categorybtn;
    private javax.swing.JTextField cat_name_txt1;
    private javax.swing.JTable category_tbl;
    private javax.swing.JButton deletercd_btn;
    private javax.swing.JLabel img_linklbl;
    private javax.swing.JLabel img_uploadlbl;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel search_lbl;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton upload_imgbtn1;
    private javax.swing.JLabel warning_lbl;
    // End of variables declaration//GEN-END:variables
byte[] Photo = null; 
String FileName; 
}

