/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.innovatrasolution.ui;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
//import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author junai
 */
public class ManageProducts extends javax.swing.JFrame {

            

    /**
     * Creates new form ManageProducts
     */
    public ManageProducts() {
        initComponents();
        UpdateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pdct_name_txt = new javax.swing.JTextField();
        qty_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        category_combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        pdt_dt = new com.toedter.calendar.JDateChooser();
        add_pdct_btn = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        price_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New Products");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 177, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 129, 29));

        pdct_name_txt.setBackground(new java.awt.Color(102, 102, 102));
        pdct_name_txt.setForeground(new java.awt.Color(255, 255, 255));
        pdct_name_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel1.add(pdct_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 262, 29));

        qty_txt.setBackground(new java.awt.Color(102, 102, 102));
        qty_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qty_txt.setForeground(new java.awt.Color(255, 255, 255));
        qty_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel1.add(qty_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 262, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Price of Product");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 129, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Category");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 129, 29));

        category_combo.setBackground(new java.awt.Color(102, 102, 102));
        category_combo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        category_combo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel1.add(category_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 262, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 129, 29));

        pdt_dt.setBackground(new java.awt.Color(102, 102, 102));
        pdt_dt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel1.add(pdt_dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 260, 29));

        add_pdct_btn.setBackground(new java.awt.Color(102, 102, 102));
        add_pdct_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_pdct_btn.setText("ADD");
        add_pdct_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        add_pdct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pdct_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_pdct_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 128, 36));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatrasolution/images/Images/img-upload.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 58, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatrasolution/images/Images/crossbtn.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 0, 37, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Quantity");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 129, 29));

        price_txt.setBackground(new java.awt.Color(102, 102, 102));
        price_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        price_txt.setForeground(new java.awt.Color(255, 255, 255));
        price_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel1.add(price_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 262, 29));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Boolean CheckField(String ProductName, String ProductQty, String Category, String Date){
        
        if(!(ProductName.isEmpty() | ProductQty.isEmpty() | Category.isEmpty() | Date.isEmpty())){
            return true;
        }
        else{
            return false; 
        }
    }
    //function to get the Id of the Selected Category from Combobox 
    int FetchCategoryIndex(String Category){
        int Index = 0; 
        String url = "JDBC:sqlite:temp.db";
        Connection conn = null; 
        
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);
            
        }catch (ClassNotFoundException | SQLException ex){
            ex.getStackTrace();
        }
        String query = "SELECT * from category WHERE category_name LIKE ?;";
        
        try{
                
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, Category);
                ResultSet res = stmt.executeQuery();
                
                if(res.next()){
                    String temp = res.getString("category_id");
                    Index = Integer.parseInt(temp);
                    //System.out.println(Index);
                    res.close();
                    conn.close();
                }
               
            } catch(SQLException ex){
                ex.getStackTrace();
            }
        return Index;
    }
    
    private void add_pdct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pdct_btnActionPerformed
        // TODO add your handling code here:
        
        String ProductName = pdct_name_txt.getText();
        
        String ProductQty = qty_txt.getText().toString().trim();
        int Qty = Integer.parseInt(ProductQty);
        
        String Category = category_combo.getSelectedItem().toString();
        
      int Index = FetchCategoryIndex(Category); 
      //System.out.println(Index);
//        int index = Integer.parseInt(CategoryIndex);
        
        java.util.Date date = pdt_dt.getDate();
        String strDate = DateFormat.getDateInstance().format(date);
        
        String Unit_Price = price_txt.getText();
        int UnitPrice = Integer.parseInt(Unit_Price);
         String url = "JDBC:sqlite:temp.db";
        Connection conn = null; 
        
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);
            
        }catch (ClassNotFoundException | SQLException ex){
            ex.getStackTrace();
        }
        if( CheckField(ProductName, ProductQty, Category, strDate)){
            String query = "INSERT into Products(product_name, product_qty, date, category_id, product_price) VALUES(?,?,?,?,?);";
            try{
                
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, ProductName);
                stmt.setInt(2, Qty);
                stmt.setString(3, strDate);
                stmt.setInt(4, Index);
                stmt.setInt(5, UnitPrice);
                stmt.executeUpdate();
                ProductAddedDialog ProductDialog = new ProductAddedDialog();
                ProductDialog.setVisible(true);
                this.setVisible(false);
                
            } catch(Exception ex){
                System.out.println(ex.getStackTrace());
            }
        }
        else if( CheckField(ProductName, ProductQty, Category, strDate)){
            //Else incase of Category Textfield is null 
            System.out.println("Ehhh!!! Something Went Wrong");
        }
        
        
    }//GEN-LAST:event_add_pdct_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    private void UpdateComboBox(){
         String url = "JDBC:sqlite:temp.db";
        Connection conn = null; 
        
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);
            
        }catch (ClassNotFoundException | SQLException ex){
            ex.getStackTrace();
        }
        String query = "select *from category;";
        
        try{
                PreparedStatement stmt = conn.prepareStatement(query);
                ResultSet res = stmt.executeQuery();
                
                while(res.next()){
                    category_combo.addItem(res.getString("category_name"));
                }
                res.close();
                conn.close();
                
            } catch(SQLException ex){
                ex.getStackTrace();
            }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_pdct_btn;
    private javax.swing.JComboBox<String> category_combo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pdct_name_txt;
    private com.toedter.calendar.JDateChooser pdt_dt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTextField qty_txt;
    // End of variables declaration//GEN-END:variables
}
