/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.innovatrasolution.ui;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author junai
 */

public class SearchProducts extends javax.swing.JFrame {

    /**
     * Creates new form SearchProducts
     */
    
    public SearchProducts() {
        initComponents();
        
        product_tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        //product_tbl.getTableHeader().setOpaque(false);
        product_tbl.getTableHeader().setBackground(new Color(32,136,203));
        product_tbl.getTableHeader().setForeground(new Color(255,255,255));
        product_tbl.setRowHeight(25);   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_tbl = new javax.swing.JTable();
        get_all_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatrasolution/images/Images/crossbtn.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Products");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 786, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatrasolution/images/Images/search-24.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 30, 30));

        search_txt.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 50, 528, 34));

        search_btn.setBackground(new java.awt.Color(0, 0, 204));
        search_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("Search");
        search_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        search_btn.setContentAreaFilled(false);
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 50, 90, 34));

        product_tbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Product Name", "Category", "Quantity", "Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        product_tbl.setFocusable(false);
        product_tbl.setGridColor(new java.awt.Color(255, 255, 255));
        product_tbl.setIntercellSpacing(new java.awt.Dimension(0, 0));
        product_tbl.setOpaque(false);
        product_tbl.setRowHeight(25);
        product_tbl.setSelectionBackground(new java.awt.Color(232, 57, 93));
        product_tbl.setShowVerticalLines(false);
        product_tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(product_tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 790, 280));

        get_all_btn.setBackground(new java.awt.Color(0, 0, 204));
        get_all_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        get_all_btn.setForeground(new java.awt.Color(255, 255, 255));
        get_all_btn.setText("Get All Products");
        get_all_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        get_all_btn.setContentAreaFilled(false);
        get_all_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_all_btnActionPerformed(evt);
            }
        });
        jPanel1.add(get_all_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 120, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void get_all_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_all_btnActionPerformed
        // TODO add your handling code here:
        String url = "JDBC:sqlite:temp.db";
        Connection conn = null; 
        DefaultTableModel TbleModel = (DefaultTableModel)product_tbl.getModel();
        TbleModel.setRowCount(0);
        
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);
            
        }catch (ClassNotFoundException | SQLException ex){
            ex.getStackTrace();
        }
        
        String query = "SELECT a.product_id, a.product_name, a.product_price, a.product_qty, b.category_name from Products a, Category b where a.category_id = b.category_id;";
        try{
            PreparedStatement stmt = conn.prepareStatement(query);
                
                ResultSet res =stmt.executeQuery();
                
                while(res.next()){
                    String id = String.valueOf(res.getInt("product_id")); 
                    String ProductName = res.getString("product_name");
                    String CategoryName = res.getString("category_name");
                    String Quantity = String.valueOf(res.getInt("product_qty"));
                    String Price = String.valueOf(res.getInt("product_price"));
         
                    
                    String data[] = {id,ProductName, CategoryName, Quantity,Price};
                    DefaultTableModel TblModel = (DefaultTableModel)product_tbl.getModel();
                    TblModel.addRow(data);
                }
                res.close();
                conn.close();
                
        }catch(SQLException ex){
            ex.getStackTrace();
        }
    }//GEN-LAST:event_get_all_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        String ToSearch = search_txt.getText();
        String url = "JDBC:sqlite:temp.db";
        Connection conn = null; 
        
        DefaultTableModel TbleModel = (DefaultTableModel)product_tbl.getModel();
        TbleModel.setRowCount(0);
        
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection(url);
            
        }catch (ClassNotFoundException | SQLException ex){
            ex.getStackTrace();
        }
        
        String query = "SELECT a.product_id, a.product_name, a.product_qty, b.category_name from Products a, Category b where a.category_id = b.category_id and product_name = ?;";
        try{
            PreparedStatement stmt = conn.prepareStatement(query);
                
                stmt.setString(1, ToSearch);
                ResultSet res =stmt.executeQuery();
                
                if(res.next()){
                    String id = String.valueOf(res.getInt("product_id")); 
                    String ProductName = res.getString("product_name");
                    String CategoryName = res.getString("category_name");
                    String Quantity = String.valueOf(res.getInt("product_qty"));
                    String Price = String.valueOf(res.getInt("product_price"));
         
                    
                    String data[] = {id,ProductName, CategoryName,Quantity,Price};
                    DefaultTableModel TblModel = (DefaultTableModel)product_tbl.getModel();
                    TblModel.addRow(data);
                }
                else{
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f,"Record Not Found!.","Alert",JOptionPane.WARNING_MESSAGE);
                }
                res.close();
                conn.close();
                
        }catch(SQLException ex){
            ex.getStackTrace();
        }
        
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton get_all_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable product_tbl;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_txt;
    // End of variables declaration//GEN-END:variables
}
